/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/suprajs/cyclonedds-project/src/core/idl/Telemetry.idl
  Source: /home/suprajs/cyclonedds-project/build_dds/src/dds_io/Telemetry.hpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#ifndef DDSCXX__HOME_SUPRAJS_CYCLONEDDS_PROJECT_BUILD_DDS_SRC_DDS_IO_TELEMETRY_HPP_30FFFF1D7B3FB71B2043765D0647CD66
#define DDSCXX__HOME_SUPRAJS_CYCLONEDDS_PROJECT_BUILD_DDS_SRC_DDS_IO_TELEMETRY_HPP_30FFFF1D7B3FB71B2043765D0647CD66

#include <utility>
#include <ostream>
#include <cstdint>
#include <string>

namespace Telemetry
{
class Message
{
private:
 std::string sensor_id_;
 double value_ = 0.0;
 std::string units_;
 uint64_t seq_ = 0;

public:
  Message() = default;

  explicit Message(
    const std::string& sensor_id,
    double value,
    const std::string& units,
    uint64_t seq) :
    sensor_id_(sensor_id),
    value_(value),
    units_(units),
    seq_(seq) { }

  const std::string& sensor_id() const { return this->sensor_id_; }
  std::string& sensor_id() { return this->sensor_id_; }
  void sensor_id(const std::string& _val_) { this->sensor_id_ = _val_; }
  void sensor_id(std::string&& _val_) { this->sensor_id_ = std::move(_val_); }
  double value() const { return this->value_; }
  double& value() { return this->value_; }
  void value(double _val_) { this->value_ = _val_; }
  const std::string& units() const { return this->units_; }
  std::string& units() { return this->units_; }
  void units(const std::string& _val_) { this->units_ = _val_; }
  void units(std::string&& _val_) { this->units_ = std::move(_val_); }
  uint64_t seq() const { return this->seq_; }
  uint64_t& seq() { return this->seq_; }
  void seq(uint64_t _val_) { this->seq_ = _val_; }

  bool operator==(const Message& _other) const
  {
    (void) _other;
    return sensor_id_ == _other.sensor_id_ &&
      value_ == _other.value_ &&
      units_ == _other.units_ &&
      seq_ == _other.seq_;
  }

  bool operator!=(const Message& _other) const
  {
    return !(*this == _other);
  }

};

std::ostream& operator<<(std::ostream& os, ::Telemetry::Message const& rhs);

} //namespace Telemetry

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::Telemetry::Message>::getTypeName()
{
  return "Telemetry::Message";
}

template <> constexpr bool TopicTraits<::Telemetry::Message>::isSelfContained()
{
  return false;
}

#ifdef DDSCXX_HAS_TYPELIB
template<> constexpr unsigned int TopicTraits<::Telemetry::Message>::type_map_blob_sz() { return 322; }
template<> constexpr unsigned int TopicTraits<::Telemetry::Message>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::Telemetry::Message>::type_map_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x6b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x74,  0x94,  0xef,  0xe4,  0x17,  0xfb,  0xeb, 
 0xf2,  0x6f,  0x25,  0x16,  0xcc,  0x4c,  0x5b,  0x00,  0x53,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x43,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x21,  0x00,  0x70,  0x00,  0xd9,  0x6d,  0x86,  0x6a, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x20,  0x63,  0xc1,  0x60,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xb9,  0x8b,  0x3d,  0xfb, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0xe0,  0x68,  0xc2,  0xde,  0x00, 
 0xa6,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x30,  0xb4,  0x57,  0xce,  0xfa,  0x60,  0xc2, 
 0xcf,  0x12,  0xca,  0xfc,  0xa6,  0x25,  0xc7,  0x00,  0x8e,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x1b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00,  0x54,  0x65,  0x6c,  0x65, 
 0x6d,  0x65,  0x74,  0x72,  0x79,  0x3a,  0x3a,  0x4d,  0x65,  0x73,  0x73,  0x61,  0x67,  0x65,  0x00,  0x00, 
 0x66,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x21,  0x00,  0x70,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x73,  0x65,  0x6e,  0x73,  0x6f,  0x72,  0x5f,  0x69, 
 0x64,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x76,  0x61,  0x6c,  0x75,  0x65,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x06,  0x00,  0x00,  0x00,  0x75,  0x6e,  0x69,  0x74, 
 0x73,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x73,  0x65,  0x71,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x30,  0xb4,  0x57,  0xce,  0xfa,  0x60,  0xc2,  0xcf,  0x12,  0xca,  0xfc, 
 0xa6,  0x25,  0xc7,  0xf1,  0x74,  0x94,  0xef,  0xe4,  0x17,  0xfb,  0xeb,  0xf2,  0x6f,  0x25,  0x16,  0xcc, 
 0x4c,  0x5b, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::Telemetry::Message>::type_info_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x74,  0x94,  0xef,  0xe4,  0x17,  0xfb,  0xeb,  0xf2,  0x6f,  0x25,  0x16, 
 0xcc,  0x4c,  0x5b,  0x00,  0x57,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x30,  0xb4,  0x57,  0xce,  0xfa,  0x60,  0xc2,  0xcf,  0x12,  0xca,  0xfc, 
 0xa6,  0x25,  0xc7,  0x00,  0x92,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPELIB

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::Telemetry::Message>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::Telemetry::Message>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::Telemetry::Message);

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::Telemetry::Message>();

namespace {
  static const volatile propvec &properties___Telemetry__Message = get_type_props<::Telemetry::Message>();
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::Telemetry::Message& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.sensor_id(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.value()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.units(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.seq()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::Telemetry::Message& instance, key_mode key) {
  const auto &props = get_type_props<::Telemetry::Message>();
  str.set_mode(cdr_stream::stream_mode::write, key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::Telemetry::Message& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.sensor_id(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.value()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.units(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.seq()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::Telemetry::Message& instance, key_mode key) {
  const auto &props = get_type_props<::Telemetry::Message>();
  str.set_mode(cdr_stream::stream_mode::read, key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::Telemetry::Message& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.sensor_id(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.value()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.units(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.seq()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::Telemetry::Message& instance, key_mode key) {
  const auto &props = get_type_props<::Telemetry::Message>();
  str.set_mode(cdr_stream::stream_mode::move, key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::Telemetry::Message& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.sensor_id(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.value()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.units(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.seq()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::Telemetry::Message& instance, key_mode key) {
  const auto &props = get_type_props<::Telemetry::Message>();
  str.set_mode(cdr_stream::stream_mode::max, key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX__HOME_SUPRAJS_CYCLONEDDS_PROJECT_BUILD_DDS_SRC_DDS_IO_TELEMETRY_HPP_30FFFF1D7B3FB71B2043765D0647CD66
