/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/suprajs/cyclonedds-project/src/core/idl/Telemetry.idl
  Source: /home/suprajs/cyclonedds-project/build_dds/src/dds_io/Telemetry.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "Telemetry.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace Telemetry
{
std::ostream& operator<<(std::ostream& os, ::Telemetry::Message const& rhs)
{
  (void) rhs;
  os << "[";
  os << "sensor_id: " << rhs.sensor_id();
  os << ", value: " << rhs.value();
  os << ", units: " << rhs.units();
  os << ", seq: " << rhs.seq();
  os << "]";
  return os;
}

} //namespace Telemetry

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::Telemetry::Message>() {
  static std::mutex mtx;
  static propvec props;
  static std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed))
    return props;
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::sensor_id
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::value
  props.push_back(entity_properties_t(1, 2, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::units
  props.push_back(entity_properties_t(1, 3, false, get_bit_bound<uint64_t>(), extensibility::ext_final, false));  //::seq
  keylist.add_key_endpoint(std::list<uint32_t>{0});

  entity_properties_t::finish(props, keylist);
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

